name: Push Data to DB
on:
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: windows-latest
    env:
      SUPABASE_CONNECTION: ${{ secrets.SUPABASE_CONNECTION }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Data Sync
      run: dotnet run --project vitalStatsVB/vitalStatsVB.vbproj
