name: Process Donation Data

on:
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest
    env:
      AWS_API: ${{ secrets.AWS_API }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
      
    - name: Fetch and process JSON data from API
      id: fetch-data
      run: |
        response=$(curl -s $AWS_API)
        
        if [ -z "$response" ]; then
          echo "Error: Empty response from API"
          exit 1
        fi
        
        body_content=$(echo "$response" | jq -r '.body')
        echo "$body_content" | jq . > donation_data.json
        
        echo "filename=donation_data.json" >> $GITHUB_OUTPUT

    - name: Upload processed data
      uses: actions/upload-artifact@v4
      with:
        name: donation-data
        path: donation_data.json